<a href="https://colab.research.google.com/github/shahzadmari/DSA_Lab/blob/main/lab4Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Roll no : 20SW067**

**Lab 3 Tasks**

**Name : Shahzad Haider**

# Task#01
# import numpy as np

 # Using the Built-in functions you learned about in the
 # previous lesson, create a 4 x 4 ndarray that only
 # contains consecutive even numbers from 2 to 32 (inclusive)



In [1]:

import numpy as np

x = np.array(np.arange(2,33,2).reshape(4,4))
# printing the dimensions of array
x.ndim


2

In [2]:
# printing the elements of the array
print(x)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


# Task 2

In [3]:
import numpy as np

# # Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# # Afterwards use Boolean indexing to pick out only the odd numbers in the array

# # Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.array(np.arange(1,26).reshape(5,5))

# # Use Boolean indexing to pick out only the odd numbers in the array
print(X)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Task 3



In [5]:
import numpy as np

# # Use Broadcasting to create a 4 x 4 ndarray that has its first
# # column full of 1s, its second column full of 2s, its third
# # column full of 3s, etc..

X = np.arange(1,5).reshape(4,1)

y = X*np.ones((1,4), dtype=int)
print(y)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [4]:
# boolean indexing
odd_nums = X[X % 2 == 1]
print(odd_nums)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
